<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Orion</RootNamespace>
    <AssemblyName>Orion</AssemblyName>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Protocol\Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Basalt.Binary" Version="0.1.0" />
    <PackageReference Include="Orion.RakNet" Version="0.1.0" />
  </ItemGroup>

</Project>
