namespace Orion.Protocol.Enums;

/// <summary>
/// Identifies the slot group within a container window (used in FullContainerName).
/// </summary>
public enum ContainerName : byte {
    AnvilInput = 0,
    AnvilMaterial = 1,
    AnvilResultPreview = 2,
    SmithingTableInput = 3,
    SmithingTableMaterial = 4,
    SmithingTableResultPreview = 5,
    Armor = 6,
    LevelEntity = 7,
    BeaconPayment = 8,
    BrewingStandInput = 9,
    BrewingStandResult = 10,
    BrewingStandFuel = 11,
    CombinedHotbarAndInventory = 12,
    CraftingInput = 13,
    CraftingOutputPreview = 14,
    RecipeConstruction = 15,
    RecipeNature = 16,
    RecipeItems = 17,
    RecipeSearch = 18,
    RecipeSearchBar = 19,
    RecipeEquipment = 20,
    RecipeBook = 21,
    EnchantingInput = 22,
    EnchantingMaterial = 23,
    FurnaceFuel = 24,
    FurnaceIngredient = 25,
    FurnaceResult = 26,
    HorseEquip = 27,
    Hotbar = 28,
    Inventory = 29,
    ShulkerBox = 30,
    TradeIngredientOne = 31,
    TradeIngredientTwo = 32,
    TradeResultPreview = 33,
    Offhand = 34,
    CompoundCreatorInput = 35,
    CompoundCreatorOutputPreview = 36,
    ElementConstructorOutputPreview = 37,
    MaterialReducerInput = 38,
    MaterialReducerOutput = 39,
    LabTableInput = 40,
    LoomInput = 41,
    LoomDye = 42,
    LoomMaterial = 43,
    LoomResultPreview = 44,
    BlastFurnaceIngredient = 45,
    SmokerIngredient = 46,
    TradeTwoIngredientOne = 47,
    TradeTwoIngredientTwo = 48,
    TradeTwoResultPreview = 49,
    GrindstoneInput = 50,
    GrindstoneAdditional = 51,
    GrindstoneResultPreview = 52,
    StonecutterInput = 53,
    StonecutterResultPreview = 54,
    CartographyInput = 55,
    CartographyAdditional = 56,
    CartographyResultPreview = 57,
    Barrel = 58,
    Cursor = 59,
    CreatedOutput = 60,
    SmithingTableTemplate = 61,
    CrafterLevelEntity = 62,
    DynamicContainer = 63,
    RecipeFood = 64,
    RecipeBlocks = 65,
    RecipeFurnaceItems = 66
}
